name: myhero
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.34.0
  flame_audio: ^2.11.12
  flame_tiled: ^1.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flame_test: ^2.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/images/character/
    - assets/images/bullet/
    - assets/images/button/
    - assets/audio/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/SPRITE_PORTRAIT.png
